CREATE TABLE TX_TRANSACTION (
  ID                BIGINT NOT NULL AUTO_INCREMENT,
  ID_USER           BIGINT NOT NULL,
  TRANSACTION_VALUE DECIMAL(10, 2),
  ID_COST_CENTER BIGINT NOT NULL,
  ID_CATEGORY BIGINT NOT NULL,
  DESCRIPTION varchar(512),
  PRIMARY KEY (ID)
);